#!/bin/sh
set -eu

command="${1:-}"
shift || true
case "$command" in
  add)
    printf 'add %s\n' "$*" >> "$BOOTSTRAP_TEST_CALL_LOG"
    ;;
  ping)
    printf '{"ok":true,"server":"%s"}\n' "${1:-}"
    ;;
  tools)
    case "${1:-}" in
      openviking)
        printf '%s\n' 'memory_search memory_read memory_remember health'
        ;;
      websearch)
        printf '%s\n' \
          'web_search read_url x_search vertical_search grounded_search travel_search market_data finance_documents drug_search clinical_trials weather_search geo_search company_search aviation_search provider_status health'
        ;;
      firecrawl)
        printf '%s\n' \
          'firecrawl_scrape firecrawl_map firecrawl_search firecrawl_research_search_papers firecrawl_research_inspect_paper firecrawl_research_related_papers firecrawl_research_read_paper firecrawl_research_search_github health'
        ;;
      meeting)
        printf '%s\n' \
          'create_upload start_transcription search_meetings get_meeting_transcript meeting_status job_status cancel_job health'
        ;;
      image)
        printf '%s\n' 'create_upload start_generation start_edit job_status cancel_job health'
        ;;
      video)
        printf '%s\n' 'create_audio_upload start_generation job_status cancel_job health'
        ;;
      pdfreader)
        printf '%s\n' \
          'create_upload start_read start_wechat_read wechat_archive_status job_status cancel_job health'
        ;;
      download)
        printf '%s\n' 'start_download job_status cancel_job health'
        ;;
      dashi)
        printf '%s\n' \
          'profile_status start_bazi_reading start_iching_reading start_qimen_reading start_ziwei_reading job_status cancel_job health'
        ;;
      *) exit 1 ;;
    esac
    ;;
  shutdown)
    printf '%s\n' '{"shutdown":true}'
    ;;
  *) exit 1 ;;
esac
